### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ryantm** [semaphoreci/agent#236]
Hi.

I would like to package the semaphoreci-agent for use with self-hosted CI runners on NixOS in the nixpkgs repository. Currently, this repository is missing a LICENSE file, COPYING file, or SPDX license annotations in source files, meaning (unless I missed the indication elsewhere) it will have to be considered "unfree" and not be cached automatically by NixOS's caching infrastructure.

Also, my employer and your customer, Replit, would like to use NixOS self-hosted runners and this would make it easier on us.

Could you consider adding a open source software license file, or making a declaration of the license of this source code in this issue?

Thanks,
Ryan Mulligan

**Comment by lucianoliberti** [comment]
@ryantm thanks for flagging this up. We'll assess it, thanks

**Comment by lucaspin** [comment]
@ryantm license added in https://github.com/semaphoreci/agent/pull/245.
